### ISSUE TITLE
Add junit test report in github actions

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#452]
When a Junit test fails, its hard to identify which test had failed because of the size of the log file.
A github action to publish the Junit test report will be useful.

```
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
```
