### ISSUE TITLE
Sink Connector Light for MySQL falls behind after a while

### ISSUE THREAD

**Issue by meysammeisam** [Altinity/clickhouse-sink-connector#598]
We use the light version to replicate our RDS Mysql data to CH. In most cases, it works fine, but for some cases in which the source DB is relatively large with a high write rate, it falls behind after a few hours. We have tried these but none seems to be a proper solution:
- `OPTIMIZE TABLE <ABC> FINAL` on CH
- Restarting the Sink Connector

The config file looks like:

```yaml
# clickhouse-sink-connector
database.hostname: "mysql.rds.amazonaws.com"
database.port: "3306"
database.user: "USER"
database.password: "PASS"
database.server.name: "SINK_TABLE_ABC"
database.server.id: 1014065039
database.include.list: "db"
table.include.list: "db.ABC"
clickhouse.server.url: "127.0.0.1"
clickhouse.server.user: "USER2"
clickhouse.server.pass: "PASS2"
clickhouse.server.port: "8123"
clickhouse.server.database: "db"
database.allowPublicKeyRetrieval: "true"
snapshot.mode: "schema_only"
slot.name: "ch_sink_1"
connector.class: "io.debezium.connector.mysql.MySqlConnector"
offset.flush.interval.ms: 10000
offset.storage: "io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore"
offset.storage.offset.storage.jdbc.offset.table.name: "altinity_sink_connector.db_ABC_replica_source_info"
offset.storage.jdbc.url: "jdbc:clickhouse://127.0.0.1:8123/altinity_sink_connector"
offset.storage.jdbc.user: "USER2"
offset.storage.jdbc.password: "PASS2"
offset.storage.offset.storage.jdbc.offset.table.ddl: "CREATE TABLE if not exists %s
(
    `id` String,
    `offset_key` String,
    `offset_val` String,
    `record_insert_ts` DateTime,
    `record_insert_seq` UInt64,
    `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY id
SETTINGS index_granularity = 8198"
offset.storage.offset.storage.jdbc.offset.table.delete: "delete from %s where 1=1"
schema.history.internal: "io.debezium.storage.jdbc.history.JdbcSchemaHistory"
schema.history.internal.jdbc.url: "jdbc:clickhouse://127.0.0.1:8123/altinity_sink_connector"
schema.history.internal.jdbc.user: "USER2"
schema.history.internal.jdbc.password: "PASS2"
schema.history.internal.jdbc.schema.history.table.ddl: "CREATE TABLE if not exists %s
(`id` VARCHAR(36) NOT NULL, `history_data` VARCHAR(65000), `history_data_seq` INTEGER, `record_insert_ts` TIMESTAMP NOT NULL, `record_insert_seq` INTEGER NOT NULL) ENGINE=ReplacingMergeTree(record_insert_seq) order by id"

schema.history.internal.jdbc.schema.history.table.name: "altinity_sink_connector.db_ABC_replicate_schema_history"
enable.snapshot.ddl: "false"
auto.create.tables: "false"
metrics.enable: "true"
metrics.port: "18107"
cli.port: 7001
thread.pool.size: 50
```

As it's captured by the Prometheus/Grafana dashboard, The lag(Source DB -> CH Lag) is zero for a while and then it starts falling behind, and no service logs are there. So it seems it stops working fully until we restart or reinitiate it

<img width="1910" alt="Screenshot 2024-05-16 at 15 27 29" src="https://github.com/Altinity/clickhouse-sink-connector/assets/3337117/b8411d46-4481-4b68-8333-796079e0ea55">
<img width="1910" alt="Screenshot 2024-05-16 at 15 29 04" src="https://github.com/Altinity/clickhouse-sink-connector/assets/3337117/d2d77154-e422-4cd8-86f2-5de54fc52b08">
<img width="1910" alt="Screenshot 2024-05-16 at 15 29 28" src="https://github.com/Altinity/clickhouse-sink-connector/assets/3337117/f3ac3f26-12f7-4f58-9fb1-2f53f68b002f">
<img width="1910" alt="Screenshot 2024-05-16 at 15 29 41" src="https://github.com/Altinity/clickhouse-sink-connector/assets/3337117/34b6cf85-2ea3-4230-8f97-8fda7e98df3c">

Are we missing anything in our configuration? Any hints are highly appreciated.

Notes: 
- The source DB has several tenths of tables, for the DBs with high change rates, we have separate Sink Connectors.
- We have no issues with other 10-20 Mysql DBs with smaller data and lower data change rates.
