### ISSUE TITLE
Add docker-compose healthcheck using sink-connector-client

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#655]
```
      healthcheck:
        test: ["CMD-SHELL", "if [ \"$$(/sink-connector-client show_replica_status)\" == \"\" ]; then exit 1; fi; exit 0"]
        interval: 60s
        timeout: 20s
        retries: 10
        start_period: 600s
```
