### ISSUE TITLE
`auto.create.tables` is not working on sink connector

### ISSUE THREAD

**Issue by hklsk** [Altinity/clickhouse-sink-connector#700]
Settings:
We are using the Sink connector version, not the lightweight version
tried the develop version & 2.2

```
  class: com.altinity.clickhouse.sink.connector.ClickHouseSinkConnector
  config:
    auto.create.tables: true
    auto.create.tables.replicated: true
    schema.evolution: true
```

Error showing:

*** TABLE METADATA not retrieved for Database(XXX), table(YYY) retrying
The sink connector has subscribed to the ddl change topic of database XXX

Please assist
